version: "3.8"
name: yone
services:
  container-1:
    image: nginx:latest
    container_name: yone-c-1
    volumes:
      - type: volume
        source: yone-c-volume
        target: "/var/www/html/"
      - type: bind
        source: "C:/Users/black/Downloads/scripts"
        target: /usr/share/nginx/html
      - type: tmpfs
        target: "/yone"
    ports:
      - "8050:80"
  container-2:
    image: nginx:latest
    container_name: yone-c-2
    volumes:
      - yone-c-volume:/usr/share/nginx/html
    ports:
      - "8040:80"
volumes:
  yone-c-volume: {}
